apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-deploy
  template:
    metadata:
      labels:
        app: test-deploy
    spec:
      containers:
      - name: test-deploy
        image: image: devguilhermevada/test-deploy:latest
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "250m"
---
apiVersion: v1
kind: Service
metadata:
  name: test-deploy-service
spec:
  type: NodePort
  selector:
    app: test-deploy
  ports:
    - port: 80
      targetPort: 80
      # Altere a porta aqui se 30080 estiver ocupada:
      nodePort: 30081
