apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-deploy
  template:
    metadata:
      labels:
        app: test-deploy
    spec:
      containers:
      - name: test-deploy
        image: DOCKER_USERNAME/test-deploy:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: test-deploy-service
spec:
  type: NodePort
  selector:
    app: test-deploy
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30080
